### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by whoiskevinrich** [ritterim/stuntman#102]
Following the instructions in the readme, I've added the following to my Startup.cs

``` csharp
    public class Startup
    {
        public readonly StuntmanOptions StuntmanOptions = new StuntmanOptions();

        public void Configuration(IAppBuilder app)
        {

            StuntmanOptions.AddUser(new StuntmanUser("ajoe")
                    .AddClaim("given_name", "Average")
                    .AddClaim("family_name", "Joe"));

            StuntmanOptions.SetUserPickerAlignment(StuntmanAlignment.Right);

            if (System.Web.HttpContext.Current.IsDebuggingEnabled)
            {
                app.UseStuntman(StuntmanOptions);
            }
        }
    }
```

and the following to my view:

``` csharp
@if (HttpContext.Current.IsDebuggingEnabled)
{
    @Html.Raw(Startup.StuntmanOptions.UserPicker(User))
}
```

However, I'm seeing "an object reference is required for the non-static field, method, or property 'Startup.StuntmanOptions'. Am I missing a step?

**Comment by kendaleiv** [comment]
Missing a `@using` on the view? Try using the full namespaced call to the `Startup` class. See [samples/UsageSampleMvc/Views/Shared/_Layout.cshtml#L38](https://github.com/ritterim/stuntman/blob/48b8d3b1d9aa50bb068820d6247188f6ce86d6f3/samples/UsageSampleMvc/Views/Shared/_Layout.cshtml#L38) for an example.

**Comment by whoiskevinrich** [comment]
I did try adding the full namespace, to no avail. I appreciate the help, this project will be quite useful.

**Comment by kendaleiv** [comment]
I don't see any obvious issues. You could clone down this repository and run the **UsageSampleMvc** to see if that works for you.

**Comment by whoiskevinrich** [comment]
Looks like there is a minor difference between the usage sample and the
readme example. The code now compiles, I just need to figure out why my
Stuntman options are being ignore. I'm perfectly prepared for it to be a
Windows Auth issue of somekind. Thanks for the help!

**Comment by kendaleiv** [comment]
If there's an error in the README.md, do you happen to know exactly what it is so we could update it?

**Comment by whoiskevinrich** [comment]
I added a pull request: https://github.com/ritterim/stuntman/pull/103

**Comment by kendaleiv** [comment]
Thanks, #103 was merged. Good to close this issue?

**Comment by whoiskevinrich** [comment]
Sounds good, thanks for the help. I haven't figured out how to create StuntmanUsers for Windows Auth, but this issue is good to go.
