### ISSUE TITLE
Does it work with Windows / Active Directory authentication?

### ISSUE THREAD

**Issue by ignatandrei** [ritterim/stuntman#114]
Does it work with Windows / Active Directory authentication?

**Comment by khalidabuhakmeh** [comment]
Hello @ignatandrei,

In short, **_yes**_.

All authentication mechanisms in ASP.NET utilize `Principals`, including Active Directory. The _source_ of these principals is not as important as the final representation in your code. Stuntman bypasses the _source_ and allows you to tweak the final representation of your user.

``` csharp
// doesn't matter if user came from
//   Active Directory,
//   Forms,
//   OR STUNTMAN 
HttpContext.User
```

Note: You will have to **turn off** Windows auth locally during development, but that is what we currently do with our Identity Server auth mechanism locally.

---

When you deploy to production, just disable Stuntman and turn on Windows Auth utilizing config transforms.

I hope that answers your question, but I am glad to answer any follow up ones too :)
