### ISSUE TITLE
Support for netcoreapp1.0

### ISSUE THREAD

**Issue by DejanMilicic** [ritterim/stuntman#142]
Could you please update nuget package for asp.net core?
https://www.nuget.org/packages/RimDev.Stuntman.AspNetCore/

Are there any reasons this package has been neglected?

**Comment by khalidabuhakmeh** [comment]
I believe we just forgot to bump the version in the `project.json` file. Also we've been waiting for VS 2017 tooling to bake.

https://github.com/ritterim/stuntman/pull/141

**Comment by khalidabuhakmeh** [comment]
https://www.nuget.org/packages/RimDev.Stuntman.AspNetCore/

should be on 1.6.0 now.
