### ISSUE TITLE
Add .NETStandard 2.0 support

### ISSUE THREAD

**Issue by joopscheer** [ritterim/stuntman#163]
The latest version 1.7.1 supports .NETStandard 1.4. It would be great if you can support for .NETStandard 2.0. Thank you!

**Comment by kendaleiv** [comment]
.NET Standard 2.0 is supported by targeting .NET Standard 1.4. Is it not working?

Also, the `vnext` branch targets .NET Standard 2.0 which also unifies everything into a single project. It's not released yet, though.

**Comment by joopscheer** [comment]
Nope. When I try to run my application a TypeLoadException is thrown.

```
Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Builder.CookieAuthenticationOptions' from assembly 'Microsoft.AspNetCore.Authentication.Cookies, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at RimDev.Stuntman.Core.IApplicationBuilderExtensions.UseStuntman(IApplicationBuilder app, StuntmanOptions options)
```

**Comment by kendaleiv** [comment]
A pre-release version of the `vnext` branch has been published to NuGet. It should support `netcoreapp2.0`.

**Comment by joopscheer** [comment]
Yes. That one works. Thank you!
