### ISSUE TITLE
Prevent duplicate user-Ids from getting adding to collection

### ISSUE THREAD

**Issue by billbogaiv** [ritterim/stuntman#18]
Currently, nothing prevents the app. from accepting multiple users with the same Id:

``` csharp
var options = new StuntmanOptions
            {
                Users = new[]
                {
                    new StuntmanUser("user-1", "User 1"),
                    new StuntmanUser("user-1", "User 2"),
                    new StuntmanUser("user-1", "User 3")
                }
            };
```

This will get confusing based on [current logic for selecting user](https://github.com/ritterim/stuntman/blob/a75db40b2d91017165de9e053cb91f1000396830/src/Core/IAppBuilderExtensions.cs#L43-L45).

**Comment by khalidabuhakmeh** [comment]
Maybe StuntmanOptions should be fluent as well?

**Comment by kendaleiv** [comment]
I don't see a reason to disallow duplicates. There could be different names associated to the same id for testing purposes -- or is that too risky / error prone and we should disallow it?

**Comment by billbogaiv** [comment]
@kendaleiv: Duplicate IDs within the same collection would prevent non-primary users from being selected. The app. uses the first user in the collection matching the requested-ID. Using the code-example from the issue desc., you may want to select `User 2` or `User 3`, but you're going to get `User 1` every time.

**Comment by billbogaiv** [comment]
Re-opening this issue due to change of scope for #20.

**Comment by billbogaiv** [comment]
Confirmed #29 works as-expected.
