### ISSUE TITLE
Internally generate user-Id

### ISSUE THREAD

**Issue by billbogaiv** [ritterim/stuntman#20]
Manually assigning a user-Id is unnecessary and should be handled automatically when a user is added to the collection.

**Comment by kendaleiv** [comment]
I assume we want to allow configuration of the id in case a developer wants to arrange sample data for the collection of users.

We could create another constructor that only requires the name and automatically generates the id, if that would help minimize configuration for cases where a specific id doesn't matter.

**Comment by billbogaiv** [comment]
Agreed this should be a constructor overload.

**Comment by billbogaiv** [comment]
Confirmed #29 works as-expected.
