### ISSUE TITLE
Ensure OWIN endpoints are not available in production

### ISSUE THREAD

**Issue by kendaleiv** [ritterim/stuntman#23]

**Comment by jrusbatch** [comment]
Wouldn't this be an application concern? Glimpse, for example, leaves it up to the application to specify custom security logic (or it can be removed entirely via a web transform). But it has no knowledge of the applications environments.

**Comment by kendaleiv** [comment]
It may be. The sample applications have the endpoints always available currently, though. At minimum, we should update the sample applications and provide the same guidance in the **README.md** in #9.
