### ISSUE TITLE
Create a Stuntman Logo

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ritterim/stuntman#28]
It would be awesome to create a logo that works both in the Nuget.org gallery, on the widget as a badge, and on the login page as a title. Also it would be great to put into the readme file.

**Comment by kendaleiv** [comment]
Stuntman now has a logo: https://github.com/ritterim/stuntman/blob/gh-pages/images/stuntman-logo.png (thanks to @hougasian for creating it!)
