### ISSUE TITLE
Colorized helmet indicators

### ISSUE THREAD

**Issue by kendaleiv** [ritterim/stuntman#54]
@hougasian had an idea for having differing helmet colors for users accomplished with a custom font.

We'd probably want to incorporate the colors into the list of items as well (perhaps a helmet in front of each item, but lower opacity, with a currently in-use one with full opacity?).

**Comment by khalidabuhakmeh** [comment]
Screenshots?

**Comment by kendaleiv** [comment]
After @hougasian re-designed the UI, we've decided to take a different direction.
