### ISSUE TITLE
Runtime specification of custom user

### ISSUE THREAD

**Issue by kendaleiv** [ritterim/stuntman#87]
Allowing runtime specification of a `StuntmanUser` might be handy for some scenarios (QA environments), where you want to impersonate a specific user not necessarily known at development time.

Or, is this something we want to avoid for any number of reasons? In terms of a QA environment, would this be _bad idea_ in terms of QA differing too much from production? Although, that might be something for users of Stuntman to determine on their own on a case-by-case basis.
## Implementation thoughts

Perhaps the UI could have a **Custom** option added to the user picker and choose-a-user screen, with the necessary fields appearing in some manner after clicking the **Custom** option.

@hougasian might have some ideas.

**Comment by khalidabuhakmeh** [comment]
It could be added, but I don't think it will be beneficial. The idea is to share user scenarios amongst team members, and by allowing you to have to do that at runtime you lose the value of sharing.

In regards to **impersonating** a specific user, that would probably be a one off for a short period of time that a developer might just want to put in code, then later take out.

**Comment by khalidabuhakmeh** [comment]
![](http://media1.giphy.com/media/zMDQIudRLFKco/giphy.gif)
